openapi: 3.0.0

info:
  title: Protogen API
  version: 1.0.0Beta
  description: Protogen API, implemented with OpenAPI Codegen

paths:
  /reservations:
    post:
      summary: Creates a reservation
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationDTO'
      responses:
        '201':
          description: Reservation added successfully

    get:
      summary: Retrieves all reservations that a user has access to
      operationId: getAllReservation
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDTO'

  /reservations/{id}:
    get:
      summary: Retrieve a reservation by id
      operationId: getReservationById
      parameters:
        - name: id
          in: path
          description: id of a reservation to retrieve
          required: true
          schema:
            type: long
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationDTO'
        '404':
          description: Reservation not found

    delete:
      summary: Remove a reservation by id
      operationId: removeReservation
      parameters:
        - name: id
          in: path
          description: id of a reservation to remove
          required: true
          schema:
            type: long
      responses:
        '204':
          description: Reservation removed successfully

    put:
      summary: update reservation by id
      operationId: updateReservationById
      parameters:
        - name: id
          in: path
          description: id of a reservation to update
          required: true
          schema:
            type: long
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationDTO'
      responses:
        '200':
          description: Reservation updated successfully
        '404':
          description: Reservation not found

  /reservations/search:
    get:
      summary: Retrieve reservations by search query
      operationId: searchReservation
      parameters:
        - name: id
          in: query
          description: id of a reservation to search
          required: false
          schema:
            type: long
        - name: userId
          in: query
          description: id of a user to search by
          required: false
          schema:
            type: long
        - name: carId
          in: query
          description: id of a car to search by
          required: false
          schema:
            type: long
        - name: fromDate
          in: query
          description: date of a reservation to search
          required: false
          schema:
            type: date
        - name: toDate
          in: query
          description: date of a reservation to search
          required: false
          schema:
            type: date
        - name: pickUpLocation
          in: query
          description: pick up location of a reservation to search
          required: false
          schema:
            type: string
        - name: dropOffLocation
          in: query
          description: drop off location of a reservation to search
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Reservation query successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDTO'
        '404':
          description: Reservation not found

components:
  schemas:
    ReservationDTO:
      type: object
      properties:
        id:
          type: long
        userId:
          type: long
        carId:
          type: long
        fromDate:
          type: date
        toDate:
          type: date
        pickUpLocation:
          type: string
        dropOffLocation:
          type: string
