openapi: 3.0.0

info:
  title: Protogen API
  version: 1.0.0Beta
  description: Protogen API, implemented with OpenAPI Codegen

paths:
  /users:
    post:
      summary: Creates a user
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: User added successfully

    get:
      summary: Retrieves all users that a user has access to
      operationId: getAllUser
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'

  /users/{id}:
    get:
      summary: Retrieve a user by id
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: id of a user to retrieve
          required: true
          schema:
            type: long
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found

    delete:
      summary: Remove a user by id
      operationId: removeUser
      parameters:
        - name: id
          in: path
          description: id of a user to remove
          required: true
          schema:
            type: long
      response:
        '204':
          description: User removed successfully

    put:
      summary: update a user by id
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: id of a user to update
          required: true
          schema:
            type: long
      requiredBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found

components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: long
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: date
        rsaId:
          type: string
