openapi: 3.0.0

info:
  title: Protogen API
  version: 1.0.0Beta
  description: Protogen API, implemented with OpenAPI Codegen

paths:
  /login/users:
    post:
      summary: login a user
      operationId: login
      parameters:
        - name: password
          in: query
          description: password of a user to login
          required: true
          schema:
            type: string
        - name: username
          in: query
          description: username of a user to login
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User login successfully
        '401':
          description: Unauthorized - Invalid credentials
        '404':
          description: User not found
        '500':
          description: Internal server error
  /users:
    post:
      summary: Creates a user
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: User added successfully

    get:
      summary: Retrieves all users that a user has access to
      operationId: getAllUser
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'

  /users/{id}:
    get:
      summary: Retrieve a user by id
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: id of a user to retrieve
          required: true
          schema:
            type: long
      responses:
        '200':
          description: Retrieve success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found

    delete:
      summary: Remove a user by id
      operationId: removeUser
      parameters:
        - name: id
          in: path
          description: id of a user to remove
          required: true
          schema:
            type: number
      responses:
        '204':
          description: User removed successfully

    put:
      summary: update a user by id
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: id of a user to update
          required: true
          schema:
            type: long
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: User updated successfully
        '404':
          description: User not found

  /users/search:
    get:
      summary: Retrieves user by search
      operationId: searchUser
      parameters:
        - name: id
          in: query
          description: id of a user to search
          required: false
          schema:
            type: number
        - name: username
          in: query
          description: username of a user to search
          required: false
          schema:
            type: string
        - name: firstName
          in: query
          description: first name of a user to search
          required: false
          schema:
            type: string
        - name: lastName
          in: query
          description: last name of a user to search
          required: false
          schema:
            type: string
        - name: dateOfBirth
          in: query
          description: date of birth of a user to search
          required: false
          schema:
            type: date
        - name: rsaId
          in: query
          description: rsa id of a user to search
          required: false
          schema:
            type: string
      responses:
        '200':
          description: User query successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found

components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: number
        username:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: date
        rsaId:
          type: string
